import Link from "next/link";
import { ArrowLeft, FileText } from "lucide-react";

export const metadata = {
  title: "Terms & Conditions | AI Smart Farming Assistant",
  description:
    "Terms and Conditions for using AI Smart Farming Assistant.",
};

function Term({ title, text }) {
  return (
    <section>
      <h2 className="text-2xl font-bold text-green-700 mb-4">
        {title}
      </h2>

      <p className="text-gray-600 leading-8">
        {text}
      </p>
    </section>
  );
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#FAFAF7]">

      {/* Hero */}

      <section className="bg-gradient-to-r from-green-700 via-green-600 to-green-500 text-white">

        <div className="max-w-5xl mx-auto px-6 py-16">

          <Link
            href="/"
            className="inline-flex items-center gap-2 text-green-100 hover:text-white mb-8"
          >
            <ArrowLeft size={18} />
            Back to Home
          </Link>

          <div className="flex items-center gap-4">

            <div className="w-14 h-14 rounded-xl bg-white/20 flex items-center justify-center">
              <FileText size={28} />
            </div>

            <div>
              <h1 className="text-4xl font-bold">
                Terms & Conditions
              </h1>

              <p className="text-green-100 mt-2">
                Last Updated: July 2026
              </p>
            </div>

          </div>

        </div>

      </section>

      {/* Content */}

      <section className="max-w-5xl mx-auto px-6 py-16">

        <div className="bg-white rounded-3xl shadow-lg p-8 md:p-12 space-y-10">

          <Term
            title="1. Acceptance of Terms"
            text="By using AI Smart Farming Assistant, you agree to these Terms & Conditions. If you do not agree, please discontinue using the application."
          />

          <Term
            title="2. Purpose of the Application"
            text="The application provides AI-powered agricultural assistance including crop disease detection, weather-based guidance, crop recommendations, irrigation advice, market information, pest management, and government scheme suggestions."
          />

          <Term
            title="3. AI Recommendations"
            text="Recommendations generated by Artificial Intelligence are intended to assist decision-making. They should not replace professional agricultural advice or local field observations."
          />

          <Term
            title="4. User Responsibilities"
            text="Users are responsible for providing accurate information such as crop details, images, and location whenever required. Incorrect information may result in less accurate recommendations."
          />

          <Term
            title="5. Crop Images"
            text="Images uploaded for disease detection should clearly show the affected part of the plant. Blurry or unrelated images may reduce prediction accuracy."
          />

          <Term
            title="6. Availability"
            text="Some features depend on external services such as weather providers or AI models. Temporary interruptions may affect the availability of certain recommendations."
          />

          <Term
            title="7. Intellectual Property"
            text="All application content, branding, designs, and software remain the property of the project owners unless otherwise stated."
          />

          <Term
            title="8. Limitation of Liability"
            text="AI Smart Farming Assistant is not liable for farming decisions, crop losses, financial losses, or damages resulting from the use of AI-generated recommendations."
          />

          <Term
            title="9. Updates"
            text="These Terms & Conditions may be updated periodically to improve our services or comply with applicable regulations."
          />

          <Term
            title="10. Contact"
            text="If you have questions regarding these Terms & Conditions, please contact us through the Contact page."
          />

        </div>

      </section>

    </main>
  )
}

